openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation of the application "Water Tracker"
tags:
  - name: Auth
    description: Operations about Auth
  - name: User
    description: Operations about User
  - name: Water
    description: Operations about Water
servers:
  - url: http://localhost:3000
  - url: https://watertrackerbackend-5ymk.onrender.com
paths:
  /auth/signup:
    post:
      $ref: '../swagger/paths/auth/singUpPost.yaml'
  /auth/signin:
    post:
      $ref: '../swagger/paths/auth/singInPost.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refreshPost.yaml'
  /user/{id}:
    get:
      $ref: '../swagger/paths/user/{id}/userGet.yaml'
    patch:
      $ref: '../swagger/paths/user/{id}/userUpdatePatch.yaml'
  /user/{id}/avatar:
    patch:
      $ref: '../swagger/paths/user/{id}/userAvatarUpdate.yaml'
  /water/water-entry:
    post:
      $ref: '../swagger/paths/water/waterPost.yaml'
  /water/water-entry/{id}:
    patch:
      $ref: '../swagger/paths/water/{id}/waterByIdPatch.yaml'
    delete:
      $ref: '../swagger/paths/water/{id}/waterByIdDelete.yaml'
  /water/today:
    get:
      $ref: '../swagger/paths/water/dailyWaterDataGet.yaml'
  /water/month/:month:
    get:
      $ref: '../swagger/paths/water/monthlyWaterDataGet.yaml'
  /water/daily-norma:
    patch:
      $ref: '../swagger/paths/water/dailyWaterPatch.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
